Webapp/Controllers/CartController.cs
using HSBCReward.AppCode.BAL;
using HSBCReward.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HSBCReward.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart

        private readonly CartService _cartService;
        private readonly LoginService _loginService;

        public CartController()
        {
            _cartService = new CartService();
            _loginService = new LoginService();// Instantiate the ProductService
        }
      
        public ActionResult Index()
        {
            string userGuid = Session["EncryptedUserGuid"] as string;
           string userUid =_loginService.GetUserUid(userGuid);
            Session["CartItemCount"] = _cartService.getCartCount(userUid);

            int id = _loginService.GetUserId(userUid);
            List<product> productcart = _cartService.getCart(id);
            return View(productcart);

        }

        public ActionResult DeleteItem(string productCode)
        {
            int cartCode = Convert.ToInt32(productCode);
            bool succeeded = _cartService.deleteProduct(cartCode);
            if (succeeded)
            {
                return Json(new { success = true });
            }
            else
            {
                // Return a JSON object with error status
                return Json(new { success = false });
            }

        }

        public ActionResult UpdateQuantity(int productId, int quantity)
        {
            if (productId != 0 && quantity !=0)
            {
                bool succeeded = _cartService.updateProductQty(productId, quantity);
                if (succeeded)
                {
                    return Json(new { success = true });
                }
                else
                {
                    // Return a JSON object with error status
                    return Json(new { success = false });
                }
            }
            return Json(new { success = false });

        }

    }
}

Webapp/Controllers/OrderHistoryController.cs
using HSBCReward.AppCode.BAL;
using HSBCReward.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HSBCReward.Controllers
{
    public class OrderHistoryController : Controller
    {
        private readonly CartService _cartService;
        private readonly LoginService _loginService;

        public OrderHistoryController()
        {
            _cartService = new CartService();
            _loginService = new LoginService();
        }
        public ActionResult Index()
        {
            string userGuid = Session["EncryptedUserGuid"] as string;
            string userUid = _loginService.GetUserUid(userGuid);
            int id = _loginService.GetUserId(userUid);
            List<OrderHistoryModel> orderhistory = _cartService.orderHistory(id);
            return View(orderhistory);

        }

        public ActionResult GetOrderDetails(string orderId)
        {


            OrderHistoryModel orderdetails = _cartService.getorderdetailspopup(orderId);


            return Json(orderdetails, JsonRequestBehavior.AllowGet);
        }
    }
}

Webapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title HSBCReward</title>
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdn.rawgit.com/tonystar/bootstrap-float-label/v4.0.2/bootstrap-float-label.min.css" />

    <link rel="stylesheet" href="~/Content/font-awesome.min.css">
    <link rel="stylesheet" href="~/fonts/UniversArabicforHSBC.woff">

    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/native.css">

    <link rel="stylesheet" href="~/Content/theme.css">
    <link rel="stylesheet" href="~/Content/nouislider.css">

    <link rel="shortcut icon" href="~/favicon.ico">
    <link rel="stylesheet" href="~/Content/style.css">
</head>
<body>




    <div class="container-fluid topNav">
        <div class="row">
            <div class="col-3 col-md-3">
                <ul class="list-group list-group-horizontal">
                    <li class="list-group-item pl-0"><a href="@Url.Action("FAQ", "Home" , new { area="" })">FAQ</a></li>
                    <li class="list-group-item"><a href="@Url.Action("TnC", "Home" , new { area="" })">T&C</a></li>

                </ul>
            </div>
            <div class="col-9 col-md-9 rightNavT">
                <ul class="list-group list-group-horizontal justify-content-end">
                    <li class="list-group-item d-none d-md-block d-lg-block">Welcome <span>Mr Tapan Kamal Das</span></li>
                    <li class="list-group-item d-none d-md-block d-lg-block"><span class="text-theme">Points</span> <span>541</span></li>
                    <li class="list-group-item bgBtn"><a href="javascript:void(0)">Login</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div id="backdropmenu"></div>
    <nav class="nav-header navbar sticky-top navbar-expand-lg navbar-light bg-white main-header">
        <div class="container-fluid container-main pr-0 pl-0">
            <a class="navbar-brand " href="@Url.Action(" Index", "Home" , new { area="" })">
                <img class="img-fluid" src="~/images/HSBCLogo.svg" alt="HSBC India Bank">
            </a>
            <div class="main left ml-auto" id="sidenav">
                <div class="collapse navbar-collapse sidebar-wrapper" id="navbarsExample07">
                    <!-- sidebar-header  -->
                    <div class="sidebar-header">
                        <div class="user-info">
                            <a href="#" class="text-white">
                                <h6 class="user-name">Anand Radhakrishnan</h6>
                            </a>
                            <a href="#" class="text-white">
                                <h6 class="user-name font-weight-normal pt-0">Point: 5000</h6>
                            </a>
                        </div>
                    </div>
                    <ul class="navbar-nav mlr-auto header-mobile">

                        <!-- Features -->
                        <li class="dropdown megamenu nav-item ripple-effect-grey rounded active cardDropdwnMenu hide-mob">
                            <a class="dropdown-toggle nav-link" href="#" role="button" data-menu="caret" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img src="~/images/CVC.png" class="navImg">
                            </a>
                            <div class="dropdown-menu animation slideUpIn" aria-labelledby="navbarDropdown">
                                <div class="d-flex justify-content-center">
                                    <div class="col-md-4 col-12">
                                        <div class="cardBg"><img src="~/images/CVC.png" class="img-fluid"></div>
                                    </div>
                                </div>
                            </div>
                        </li>

                        <li class="nav-item ripple-effect-grey rounded dropdown megamenu hide-mob">
                            <a class="dropdown-toggle nav-link" href="#" role="button" data-menu="caret" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-person-fill"></i>
                            </a>
                            <div class="dropdown-menu animation slideUpIn" aria-labelledby="navbarDropdown">
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item"><a href="@Url.Action("Index", "OrderHistory" , new { area="" })">Order History</a></li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item visible-mob"><a href="javascript:void(0)" class="nav-link">Order History</a></li>
                        <li class="nav-item visible-mob"><a href="javascript:void(0)" class="nav-link">FAQ</a></li>
                        <li class="nav-item visible-mob"><a href="javascript:void(0)" class="nav-link">T&C</a></li>
                        <li class="nav-item visible-mob"><a href="javascript:void(0)" class="nav-link">Logout</a></li>
                    </ul>

                </div>
            </div>

            <ul class="navbar-nav header-mobile align-items-center" style="flex-direction: row; padding-top:5px;">

                <li class="nav-item ripple-effect-grey rounded searchli hide-mob">
                    <div class="search-txtWrp">
                        <input type="text" name="" class="search-input">
                        <i class="bi bi-search abSearch"></i>
                    </div>
                    <a class=" nav-link bt0 searchdrtogle" href="#" role="button">
                        <i class="bi bi-search sIcon"></i>
                        <i class="bi bi-x-circle sClose"></i>
                    </a>

                </li>
                <li class="dropdown megamenu nav-item ripple-effect-grey rounded active cardDropdwnMenu visible-mob">
                    <a class="dropdown-toggle" href="#" role="button" data-menu="caret" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="~/images/CVC.png" class="navImg">

                    </a>
                    <div class="dropdown-menu animation slideUpIn" aria-labelledby="navbarDropdown">
                        <div class="d-flex justify-content-center">
                            <div class="col-md-4 col-4">
                                <div class="cardBg"><img src="~/images/CVC.png" class="img-fluid"></div>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="nav-item navbar-icon  pr-0 bt0">
                    <a class="text-secondary cartA ripple-effect-grey" href="@Url.Action("Index", "Cart" , new { area="" })">
                        <i class="bi bi-cart"></i>
                        <span class="navbar-icon-badge bg-secondary">@Session["CartItemCount"]</span>
                    </a>
                </li>
                <li class="nav-item navbar-icon bt0 visible-mob">
                    <a href="javascript:void(0)" class="">
                        <span id="filterbutton" class="col-12   text-right pl-0 pr-0">

                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-filter" style=""><polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"></polygon></svg>
                        </span>
                    </a>
                </li>
                <li class="nav-item ripple-effect-grey rounded searchli visible-mob">
                    <div class="search-txtWrp">
                        <input type="text" name="" class="search-input">
                        <i class="bi bi-search abSearch"></i>
                    </div>
                    <a class=" bt0 searchdrtogle" href="#" role="button">
                        <i class="bi bi-search sIcon"></i>
                        <i class="bi bi-x-circle sClose"></i>
                    </a>

                </li>
                <li class="nav-item d-md-none d-lg-none">
                    <div id="menu-toggle">
                        <button class="navbar-toggler ripple-effect-grey pr-0" type="button">
                            <div id="nav-icon2">
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                            </div>
                        </button>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    @if (!(ViewContext.RouteData.Values["controller"].ToString().Equals("Home", StringComparison.OrdinalIgnoreCase) &&
        ViewContext.RouteData.Values["action"].ToString().Equals("Index", StringComparison.OrdinalIgnoreCase)) &&
        !(ViewContext.RouteData.Values["controller"].ToString().Equals("ClientProduct", StringComparison.OrdinalIgnoreCase) &&
        ViewContext.RouteData.Values["action"].ToString().Equals("Index", StringComparison.OrdinalIgnoreCase)))
    {
        <div class="breadcrumbs ms-3 mt-3 pe-1">
            <a href="@Url.Action("Index", "Home")">Home</a> <i class="bi bi-chevron-right text-danger"></i> <span class="HSBCBold">@ViewBag.Title</span>
        </div>
    }




    <div>
        @RenderBody()

        <footer class="container-fluid bg-dark">
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/native.js"></script>

    <script src="~/Scripts/custom.js"></script>
    <script src="~/Scripts/wNumb.min.js"></script>
    <script src="~/Scripts/nouislider.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script>

        $(document).ready(function () {

            var quantitiy = 0;
            $('.qty_plus').click(function (e) {
                e.preventDefault();
                var quantity = parseInt($('#qtyVal').val());
                $('#qtyVal').val(quantity + 1);

            });

            $('.qty_minus').click(function (e) {
                e.preventDefault();
                var quantity = parseInt($('#qtyVal').val());
                if (quantity > 0) {
                    $('#qtyVal').val(quantity - 1);
                }
            });

            $('.searchdrtogle').click(function () {
                $('.search-txtWrp').toggleClass('active');
                $(this).toggleClass('active');
            })

        });



    </script>

    @RenderSection("scripts", required: false)
</body>
</html>